---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels: 
    run: registry
  name: registry
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: registry
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: registry
    spec:
      containers:
      - image: davidtimm/cf-indicators:dev
        imagePullPolicy: Always
        name: registry
        command: ["/bin/registry", "--port", "80"]
        ports:
        - containerPort: 80
          hostPort: 80
          name: registry-port
        livenessProbe:
          httpGet:
            path: /metrics
            port: registry-port
          initialDelaySeconds: 5
          periodSeconds: 5
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: registry
  name: registry
  namespace: default
spec:
  ports: 
  - port: 80
    protocol: TCP
    targetPort: registry-port
  selector: 
    run: registry
  sessionAffinity: None
  type: LoadBalancer
